### ISSUE TITLE
The difference between SFU_00 to SFU_13

### ISSUE THREAD

**Issue by zqcawzs** [edwar-vhd/SFU#4]
Hi,

I see four different SFU designs under Description and I can't find any document to say what's the difference. Could you give some hints?

Thanks

**Comment by edwar-vhd** [comment]
Hi,

The firt version of the SFU is the design without redundancy un the arquitecture, the others are variations on the design to apply the TMR in the SFU, you can read the section "7.2. TMR EN LA SFU DE PPA" for details.

https://github.com/edwar-vhd/SFU-Piecewise-Polynomial-Approximation/blob/main/Implementaci%C3%B3n%20y%20evaluaci%C3%B3n%20de%20una%20unidad%20de%20funciones%20especiales%20tolerante%20a%20fallas%20basada%20en%20aproximaci%C3%B3n%20polinomial%20por%20partes.pdf

**Comment by zqcawzs** [comment]
> Hi,
> 
> The firt version of the SFU is the design without redundancy un the arquitecture, the others are variations on the design to apply the TMR in the SFU, you can read the section "7.2. TMR EN LA SFU DE PPA" for details.
> 
> https://github.com/edwar-vhd/SFU-Piecewise-Polynomial-Approximation/blob/main/Implementaci%C3%B3n%20y%20evaluaci%C3%B3n%20de%20una%20unidad%20de%20funciones%20especiales%20tolerante%20a%20fallas%20basada%20en%20aproximaci%C3%B3n%20polinomial%20por%20partes.pdf

Any chance to provide an English version? Thanks.
